import { useState, useRef, useEffect } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { queryClient } from "@/lib/queryClient";
import { useSettingsAutoSave } from "@/hooks/useSettingsAutoSave";
import GlassCard from "@/components/GlassCard";
import ZoneManagement from "@/pages/ZoneManagement";
import QRCodeImage from "@/components/QRCodeImage";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { Separator } from "@/components/ui/separator";
import { useToast } from "@/hooks/use-toast";
import { MapPin, Eye, QrCode, RefreshCw, Copy, AlertTriangle, Zap, RotateCcw, Shield, ListChecks, Plus, Trash2, ArrowUp, ArrowDown, Pencil, Check, X } from "lucide-react";
import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from "@/components/ui/tooltip";

interface MusterPoint {
  id: string;
  name: string;
  displayOrder: number;
  isActive: boolean;
}

export default function EmergencySettings() {
  const { currentSettings, handleInputChange } = useSettingsAutoSave();
  const { toast } = useToast();
  const [incidentMonitorGenerating, setIncidentMonitorGenerating] = useState(false);
  const [showIncidentMonitorQr, setShowIncidentMonitorQr] = useState(false);
  const incidentMonitorAutoGeneratedRef = useRef(false);
  const [newOptionText, setNewOptionText] = useState("");

  // Muster Points state
  const [newMusterPointName, setNewMusterPointName] = useState("");
  const [editingMusterId, setEditingMusterId] = useState<string | null>(null);
  const [editingMusterName, setEditingMusterName] = useState("");
  const [deletingMusterId, setDeletingMusterId] = useState<string | null>(null);

  // Muster Points queries + mutations
  const { data: musterPointsList, isLoading: musterPointsLoading } = useQuery<MusterPoint[]>({
    queryKey: ["/api/muster-points"],
    staleTime: 10 * 1000,
  });

  const invalidateMusterPoints = () => {
    queryClient.invalidateQueries({ queryKey: ["/api/muster-points"] });
    queryClient.invalidateQueries({ queryKey: ["/api/settings/quick-setup-status"] });
  };

  const addMusterPointMutation = useMutation({
    mutationFn: async (name: string) => {
      const nextOrder = (musterPointsList?.length ?? 0) + 1;
      const res = await apiRequest("POST", "/api/muster-points", { name, displayOrder: nextOrder });
      return res.json();
    },
    onSuccess: () => {
      invalidateMusterPoints();
      setNewMusterPointName("");
      toast({ title: "Muster point added" });
    },
    onError: () => toast({ title: "Error", description: "Could not add muster point.", variant: "destructive" }),
  });

  const updateMusterPointMutation = useMutation({
    mutationFn: async ({ id, name, displayOrder, isActive }: { id: string; name: string; displayOrder: number; isActive: boolean }) => {
      const res = await apiRequest("PUT", `/api/muster-points/${id}`, { name, displayOrder, isActive });
      return res.json();
    },
    onSuccess: () => {
      invalidateMusterPoints();
      setEditingMusterId(null);
    },
    onError: () => toast({ title: "Error", description: "Could not update muster point.", variant: "destructive" }),
  });

  const deleteMusterPointMutation = useMutation({
    mutationFn: async (id: string) => {
      const res = await apiRequest("DELETE", `/api/muster-points/${id}`);
      return res.json();
    },
    onSuccess: () => {
      invalidateMusterPoints();
      setDeletingMusterId(null);
      toast({ title: "Muster point deleted" });
    },
    onError: () => toast({ title: "Error", description: "Could not delete muster point.", variant: "destructive" }),
  });

  const moveMusterPoint = (index: number, direction: "up" | "down") => {
    const list = musterPointsList ?? [];
    const swapIndex = direction === "up" ? index - 1 : index + 1;
    if (swapIndex < 0 || swapIndex >= list.length) return;
    const a = list[index];
    const b = list[swapIndex];
    updateMusterPointMutation.mutate({ id: a.id, name: a.name, displayOrder: b.displayOrder, isActive: a.isActive });
    updateMusterPointMutation.mutate({ id: b.id, name: b.name, displayOrder: a.displayOrder, isActive: b.isActive });
  };

  const { data: musterSettings } = useQuery<{ statusOptionsEnabled: boolean; statusOptions: string[] }>({
    queryKey: ["/api/muster/settings"],
    staleTime: 10 * 1000,
  });

  const saveMusterSettingsMutation = useMutation({
    mutationFn: async (payload: { statusOptionsEnabled?: boolean; statusOptions?: string[] }) => {
      const res = await apiRequest("PUT", "/api/muster/settings", payload);
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/muster/settings"] });
      toast({ title: "Saved", description: "Muster status options updated." });
    },
    onError: () => {
      toast({ title: "Error", description: "Failed to save muster settings.", variant: "destructive" });
    },
  });

  const { data: currentUser } = useQuery<{ id: string; username: string; customerId: string; role: string }>({
    queryKey: ["/api/auth/me"],
  });

  const { data: users } = useQuery<Array<{ id: string; role: string; isCurrentUser?: boolean }>>({
    queryKey: ["/api/users"],
  });

  const sessionUserFromList = users?.find((u: any) => u.isCurrentUser);
  const isAdminUser = sessionUserFromList?.role === 'admin' || currentUser?.role === 'admin';

  const { data: settings } = useQuery<{ incidentManagerUrlId?: string }>({
    queryKey: ["/api/settings"],
  });

  useEffect(() => {
    if (!isAdminUser || !settings || (settings as any).incidentManagerUrlId || incidentMonitorAutoGeneratedRef.current) return;
    incidentMonitorAutoGeneratedRef.current = true;
    apiRequest("POST", "/api/admin/incident-monitor/generate")
      .then((res) => { if (res.ok) queryClient.invalidateQueries({ queryKey: ["/api/settings"] }); })
      .catch(() => {});
  }, [isAdminUser, settings]);

  return (
    <div className="space-y-6">
      {/* Muster Points */}
      <GlassCard className="dark:glass-dark">
        <div className="flex items-center mb-4">
          <MapPin className="mr-3 text-red-600 dark:text-red-400 shrink-0" size={22} />
          <div>
            <h3 className="text-base font-semibold text-fixed">Muster Points</h3>
            <p className="text-xs text-variable mt-0.5">
              These are the physical assembly points where people gather and are accounted for during an evacuation. This is separate from Zones below, which control zone-specific emergencies.
            </p>
          </div>
        </div>

        {musterPointsLoading ? (
          <p className="text-sm text-variable py-2">Loading…</p>
        ) : (musterPointsList ?? []).length === 0 ? (
          <p className="text-sm text-variable py-2 italic">No muster points configured. Add one below.</p>
        ) : (
          <div className="space-y-2 mb-3">
            {(musterPointsList ?? []).map((point, index) => {
              const list = musterPointsList ?? [];
              if (deletingMusterId === point.id) {
                return (
                  <div key={point.id} className="flex items-center gap-2 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-700 rounded px-3 py-1.5">
                    <span className="flex-1 text-sm text-red-700 dark:text-red-400">Delete <strong>{point.name}</strong>?</span>
                    <Button
                      size="sm"
                      variant="destructive"
                      className="text-xs px-2 py-1 h-7"
                      disabled={deleteMusterPointMutation.isPending}
                      onClick={() => deleteMusterPointMutation.mutate(point.id)}
                    >
                      Delete
                    </Button>
                    <Button
                      size="sm"
                      variant="ghost"
                      className="text-xs px-2 py-1 h-7"
                      onClick={() => setDeletingMusterId(null)}
                    >
                      Cancel
                    </Button>
                  </div>
                );
              }
              if (editingMusterId === point.id) {
                return (
                  <div key={point.id} className="flex items-center gap-2">
                    <Input
                      className="flex-1 text-sm h-8"
                      value={editingMusterName}
                      onChange={(e) => setEditingMusterName(e.target.value)}
                      onKeyDown={(e) => {
                        if (e.key === "Enter" && editingMusterName.trim()) {
                          updateMusterPointMutation.mutate({ id: point.id, name: editingMusterName.trim(), displayOrder: point.displayOrder, isActive: point.isActive });
                        }
                        if (e.key === "Escape") setEditingMusterId(null);
                      }}
                      autoFocus
                    />
                    <Button
                      size="icon"
                      variant="ghost"
                      className="h-8 w-8 text-green-600 hover:text-green-700 hover:bg-green-50 dark:hover:bg-green-900/20"
                      disabled={!editingMusterName.trim() || updateMusterPointMutation.isPending}
                      onClick={() => updateMusterPointMutation.mutate({ id: point.id, name: editingMusterName.trim(), displayOrder: point.displayOrder, isActive: point.isActive })}
                    >
                      <Check size={14} />
                    </Button>
                    <Button
                      size="icon"
                      variant="ghost"
                      className="h-8 w-8"
                      onClick={() => setEditingMusterId(null)}
                    >
                      <X size={14} />
                    </Button>
                  </div>
                );
              }
              return (
                <div key={point.id} className="flex items-center gap-1">
                  <span className="flex-1 text-sm bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded px-3 py-1.5 text-fixed">
                    {point.name}
                  </span>
                  <Button
                    size="icon"
                    variant="ghost"
                    className="h-8 w-8 text-gray-400 hover:text-gray-600"
                    disabled={index === 0 || updateMusterPointMutation.isPending}
                    onClick={() => moveMusterPoint(index, "up")}
                  >
                    <ArrowUp size={13} />
                  </Button>
                  <Button
                    size="icon"
                    variant="ghost"
                    className="h-8 w-8 text-gray-400 hover:text-gray-600"
                    disabled={index === list.length - 1 || updateMusterPointMutation.isPending}
                    onClick={() => moveMusterPoint(index, "down")}
                  >
                    <ArrowDown size={13} />
                  </Button>
                  <Button
                    size="icon"
                    variant="ghost"
                    className="h-8 w-8 text-gray-500 hover:text-gray-700"
                    onClick={() => { setEditingMusterId(point.id); setEditingMusterName(point.name); }}
                  >
                    <Pencil size={13} />
                  </Button>
                  <Button
                    size="icon"
                    variant="ghost"
                    className="h-8 w-8 text-red-400 hover:text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20"
                    onClick={() => setDeletingMusterId(point.id)}
                  >
                    <Trash2 size={13} />
                  </Button>
                </div>
              );
            })}
          </div>
        )}

        <div className="flex items-center gap-2 pt-1">
          <Input
            placeholder="New muster point name…"
            value={newMusterPointName}
            onChange={(e) => setNewMusterPointName(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && newMusterPointName.trim()) {
                addMusterPointMutation.mutate(newMusterPointName.trim());
              }
            }}
            className="text-sm"
          />
          <Button
            size="sm"
            className="gap-1.5 shrink-0"
            disabled={!newMusterPointName.trim() || addMusterPointMutation.isPending}
            onClick={() => addMusterPointMutation.mutate(newMusterPointName.trim())}
          >
            <Plus size={14} />
            Add
          </Button>
        </div>
      </GlassCard>

<ZoneManagement />
{/* Emergency Access - Incident Manager Monitor URL */}
{isAdminUser && (
  <GlassCard className="dark:glass-dark">
    <div className="flex items-center mb-5">
      <Eye className="mr-3 text-purple-600 dark:text-purple-400" size={22} />
      <div>
        <h3 className="text-base font-semibold text-fixed">Emergency Access — Incident Manager Monitor</h3>
        <p className="text-xs text-variable mt-0.5">
          Generate a permanent read-only link for senior managers to view live evacuation status without logging in.
        </p>
      </div>
    </div>
    {currentSettings?.incidentManagerUrlId ? (
      <div className="space-y-3">
        <div className="bg-purple-50 dark:bg-purple-900/20 border border-purple-200 dark:border-purple-700 rounded-lg p-3">
          <p className="text-xs font-semibold text-purple-700 dark:text-purple-400 mb-1.5">Your Incident Manager Monitor URL</p>
          <div className="flex items-center gap-2">
            <code className="flex-1 text-xs bg-white dark:bg-slate-800 border border-purple-200 dark:border-purple-700 rounded px-2 py-1.5 text-purple-800 dark:text-purple-300 break-all font-mono select-all">
              {`${window.location.origin}/incident-monitor/${currentSettings.incidentManagerUrlId}`}
            </code>
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button
            size="sm"
            variant="outline"
            className="gap-1.5 text-xs"
            onClick={() => {
              const url = `${window.location.origin}/incident-monitor/${currentSettings.incidentManagerUrlId}`;
              navigator.clipboard.writeText(url).then(() => {
                toast({ title: "Link Copied", description: "Monitor URL copied to clipboard." });
              });
            }}
          >
            <Copy size={13} />
            Copy Link
          </Button>
          <Button
            size="sm"
            variant="outline"
            className="gap-1.5 text-xs"
            onClick={() => {
              const url = `${window.location.origin}/incident-monitor/${currentSettings.incidentManagerUrlId}`;
              window.open(url, '_blank');
            }}
          >
            <Eye size={13} />
            Preview
          </Button>
          <Button
            size="sm"
            variant="outline"
            className="gap-1.5 text-xs"
            onClick={() => setShowIncidentMonitorQr(v => !v)}
          >
            <Shield size={13} />
            {showIncidentMonitorQr ? "Hide QR" : "Show QR"}
          </Button>
          <Button
            size="sm"
            variant="outline"
            className="gap-1.5 text-xs text-red-600 hover:text-red-700 border-red-200 hover:border-red-300"
            disabled={incidentMonitorGenerating}
            onClick={async () => {
              if (!window.confirm('Regenerating the link will invalidate the old one. Anyone using the old link will lose access. Continue?')) return;
              setIncidentMonitorGenerating(true);
              try {
                const res = await apiRequest("POST", "/api/admin/incident-monitor/generate");
                if (res.ok) {
                  queryClient.invalidateQueries({ queryKey: ["/api/settings"] });
                  toast({ title: "Link Regenerated", description: "A new monitor URL has been generated." });
                } else {
                  toast({ title: "Failed", description: "Could not regenerate link.", variant: "destructive" });
                }
              } finally {
                setIncidentMonitorGenerating(false);
              }
            }}
          >
            <RotateCcw size={13} />
            {incidentMonitorGenerating ? "Regenerating…" : "Regenerate"}
          </Button>
        </div>
        {showIncidentMonitorQr && currentSettings?.incidentManagerUrlId && (
          <div className="flex flex-col items-center gap-2 p-3 bg-white rounded-lg border border-purple-200 dark:border-purple-700">
            <p className="text-xs font-semibold text-purple-700 dark:text-purple-400">QR Code — scan to open monitor</p>
            <QRCodeImage
              data={`${window.location.origin}/incident-monitor/${currentSettings.incidentManagerUrlId}`}
              size={144}
              alt="Incident Manager Monitor QR Code"
              className="w-36 h-36"
            />
          </div>
        )}
        <p className="text-xs text-variable">
          This link shows live muster data during an active emergency. Anyone with this link can view it — treat it as sensitive.
        </p>
      </div>
    ) : (
      <div className="space-y-3">
        <div className="bg-gray-50 dark:bg-gray-800/40 border border-dashed border-gray-300 dark:border-gray-600 rounded-lg p-4 text-center">
          <Eye className="mx-auto mb-2 text-gray-400" size={24} />
          <p className="text-sm text-variable">No monitor link generated yet.</p>
          <p className="text-xs text-variable mt-1">Generate a permanent URL to share with senior managers.</p>
        </div>
        <Button
          size="sm"
          className="gap-1.5 text-xs"
          disabled={incidentMonitorGenerating}
          onClick={async () => {
            setIncidentMonitorGenerating(true);
            try {
              const res = await apiRequest("POST", "/api/admin/incident-monitor/generate");
              if (res.ok) {
                queryClient.invalidateQueries({ queryKey: ["/api/settings"] });
                toast({ title: "Monitor Link Generated", description: "Share this URL with your senior managers for read-only emergency access." });
              } else {
                toast({ title: "Failed", description: "Could not generate monitor link.", variant: "destructive" });
              }
            } finally {
              setIncidentMonitorGenerating(false);
            }
          }}
        >
          <Eye size={13} />
          {incidentMonitorGenerating ? "Generating…" : "Generate Monitor Link"}
        </Button>
      </div>
    )}
  </GlassCard>
)}
      {/* Muster Status Options */}
      <GlassCard className="dark:glass-dark">
        <div className="flex items-center mb-5">
          <ListChecks className="mr-3 text-orange-600 dark:text-orange-400" size={22} />
          <div>
            <h3 className="text-base font-semibold text-fixed">Fire Marshal — Muster Status Options</h3>
            <p className="text-xs text-variable mt-0.5">
              When enabled, Fire Marshals see a dropdown on each person's row to set a status reason (e.g. "Working remotely") instead of just marking them safe.
            </p>
          </div>
        </div>

        <div className="flex items-center justify-between mb-4">
          <Label htmlFor="status-options-toggle" className="text-sm font-medium text-fixed">
            Enable status options dropdown
          </Label>
          <Switch
            id="status-options-toggle"
            checked={musterSettings?.statusOptionsEnabled ?? false}
            onCheckedChange={(checked) =>
              saveMusterSettingsMutation.mutate({ statusOptionsEnabled: checked })
            }
            disabled={saveMusterSettingsMutation.isPending}
          />
        </div>

        {musterSettings?.statusOptionsEnabled && (
          <div className="space-y-3">
            <Separator />
            <p className="text-xs text-variable pt-1">
              These options appear in the dropdown when a Fire Marshal selects a person's status during a muster. Drag to reorder is not supported — remove and re-add to change order.
            </p>
            <div className="space-y-2">
              {(musterSettings.statusOptions || []).map((option, i) => (
                <div key={i} className="flex items-center gap-2">
                  <span className="flex-1 text-sm bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded px-3 py-1.5 text-fixed">
                    {option}
                  </span>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="text-red-500 hover:text-red-700 hover:bg-red-50 dark:hover:bg-red-900/20 px-2"
                    onClick={() => {
                      const updated = musterSettings.statusOptions.filter((_, idx) => idx !== i);
                      saveMusterSettingsMutation.mutate({ statusOptions: updated });
                    }}
                    disabled={saveMusterSettingsMutation.isPending}
                  >
                    <Trash2 size={14} />
                  </Button>
                </div>
              ))}
            </div>
            <div className="flex items-center gap-2 pt-1">
              <Input
                placeholder="Add a new status option…"
                value={newOptionText}
                onChange={(e) => setNewOptionText(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && newOptionText.trim()) {
                    const updated = [...(musterSettings.statusOptions || []), newOptionText.trim()];
                    saveMusterSettingsMutation.mutate({ statusOptions: updated });
                    setNewOptionText("");
                  }
                }}
                className="text-sm"
              />
              <Button
                size="sm"
                className="gap-1.5 shrink-0"
                disabled={!newOptionText.trim() || saveMusterSettingsMutation.isPending}
                onClick={() => {
                  const updated = [...(musterSettings.statusOptions || []), newOptionText.trim()];
                  saveMusterSettingsMutation.mutate({ statusOptions: updated });
                  setNewOptionText("");
                }}
              >
                <Plus size={14} />
                Add
              </Button>
            </div>
          </div>
        )}
      </GlassCard>
    </div>
  );
}
