import { ThermalPassTemplate, ThermalElement } from "./ThermalElement";

// Professional thermal pass templates optimized for thermal printers
// Dimensions: 361px × 247px (95mm × 65mm at 96 DPI)

export const PROFESSIONAL_THERMAL_TEMPLATES: ThermalPassTemplate[] = [
  {
    id: 'visitor-corporate',
    name: 'Corporate Visitor',
    description: 'Professional corporate visitor pass with logo and QR code',
    category: 'visitor',
    width: 361,
    height: 247,
    backgroundColor: '#FFFFFF',
    borderEnabled: true,
    borderWidth: 2,
    borderColor: '#000000',
    compatiblePrinters: ['tec_b_fv4d', 'zebra_zt230', 'zebra_zt410'],
    elements: [
      // Header
      {
        id: 'header',
        type: 'text',
        x: 15,
        y: 10,
        width: 200,
        height: 25,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'fixed',
        fixedContent: 'VISITOR',
        fontFamily: 'thermal_default',
        fontSize: 18,
        fontWeight: 'bold',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 8,
        printQuality: 'high'
      },
      
      // Company Logo
      {
        id: 'company_logo',
        type: 'image',
        x: 230,
        y: 8,
        width: 120,
        height: 35,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        imageType: 'company_logo',
        scaling: 'fit',
        alignment: 'center',
        brightness: 0,
        contrast: 0,
        invert: false,
        dithering: 'floyd_steinberg',
        thermalIntensity: 6,
        printQuality: 'high'
      },

      // Separator Line
      {
        id: 'header_line',
        type: 'line',
        x: 15,
        y: 50,
        width: 330,
        height: 2,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        thickness: 2,
        style: 'solid',
        color: '#000000',
        lineType: 'horizontal',
        thermalIntensity: 8
      },

      // Visitor Name
      {
        id: 'visitor_name',
        type: 'text',
        x: 15,
        y: 65,
        width: 200,
        height: 30,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'variable',
        variableSource: 'visitor_name',
        fontFamily: 'thermal_default',
        fontSize: 16,
        fontWeight: 'bold',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: true,
        textOverflow: 'ellipsis',
        maxLines: 2,
        thermalIntensity: 7,
        printQuality: 'high'
      },

      // Company Name
      {
        id: 'visitor_company',
        type: 'text',
        x: 15,
        y: 100,
        width: 200,
        height: 20,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'variable',
        variableSource: 'visitor_company',
        fontFamily: 'thermal_default',
        fontSize: 12,
        fontWeight: 'normal',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: true,
        textOverflow: 'ellipsis',
        thermalIntensity: 6,
        printQuality: 'normal'
      },

      // Host Label
      {
        id: 'host_label',
        type: 'text',
        x: 15,
        y: 130,
        width: 40,
        height: 15,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'fixed',
        fixedContent: 'Host:',
        fontFamily: 'thermal_default',
        fontSize: 10,
        fontWeight: 'normal',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 6,
        printQuality: 'normal'
      },

      // Host Name
      {
        id: 'host_name',
        type: 'text',
        x: 60,
        y: 130,
        width: 155,
        height: 15,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'variable',
        variableSource: 'host_name',
        fontFamily: 'thermal_default',
        fontSize: 10,
        fontWeight: 'normal',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: false,
        textOverflow: 'ellipsis',
        thermalIntensity: 6,
        printQuality: 'normal'
      },

      // Date and Time
      {
        id: 'datetime',
        type: 'text',
        x: 15,
        y: 150,
        width: 100,
        height: 15,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'variable',
        variableSource: 'check_in_time',
        fontFamily: 'thermal_default',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 5,
        printQuality: 'normal'
      },

      // QR Code
      {
        id: 'qr_code',
        type: 'qr_code',
        x: 230,
        y: 60,
        width: 115,
        height: 115,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        dataType: 'visitor_data',
        includeFields: {
          visitor_id: true,
          visitor_name: true,
          company: true,
          check_in_time: true,
          expiry_time: true,
          host: true,
          purpose: false,
          phone: false,
          email: false,
          custom_fields: false
        },
        errorCorrection: 'M',
        quietZone: 2,
        moduleSize: 1,
        printMethod: 'native_qr',
        thermalIntensity: 7
      },

      // Footer Text
      {
        id: 'footer',
        type: 'text',
        x: 15,
        y: 190,
        width: 200,
        height: 12,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'fixed',
        fixedContent: 'Please return to reception when leaving',
        fontFamily: 'thermal_default',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: true,
        textOverflow: 'clip',
        thermalIntensity: 5,
        printQuality: 'normal'
      },

      // Badge ID
      {
        id: 'badge_id',
        type: 'text',
        x: 15,
        y: 210,
        width: 100,
        height: 12,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'variable',
        variableSource: 'visitor_id',
        fontFamily: 'thermal_default',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 5,
        printQuality: 'normal'
      },

      // Security Barcode
      {
        id: 'security_barcode',
        type: 'barcode',
        x: 230,
        y: 190,
        width: 115,
        height: 40,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        dataType: 'visitor_id',
        barcodeType: 'code128',
        showText: true,
        textPosition: 'below',
        barHeight: 30,
        narrowBarWidth: 1,
        wideBarWidth: 2,
        thermalIntensity: 7,
        printQuality: 'high'
      }
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: '1.0',
    isReadOnly: false
  },

  {
    id: 'contractor-safety',
    name: 'Contractor Safety Pass',
    description: 'Safety-compliant contractor pass with H&S indicators',
    category: 'contractor',
    width: 361,
    height: 247,
    backgroundColor: '#FFFFE0',
    borderEnabled: true,
    borderWidth: 3,
    borderColor: '#FF6600',
    compatiblePrinters: ['tec_b_fv4d', 'zebra_zt230', 'zebra_zt410'],
    elements: [
      // Header
      {
        id: 'header',
        type: 'text',
        x: 15,
        y: 8,
        width: 180,
        height: 20,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'fixed',
        fixedContent: 'CONTRACTOR',
        fontFamily: 'thermal_default',
        fontSize: 16,
        fontWeight: 'bold',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#FF6600',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 8,
        printQuality: 'high'
      },

      // Company Logo
      {
        id: 'company_logo',
        type: 'image',
        x: 250,
        y: 5,
        width: 100,
        height: 25,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        imageType: 'company_logo',
        scaling: 'fit',
        alignment: 'center',
        brightness: 0,
        contrast: 0,
        invert: false,
        dithering: 'floyd_steinberg',
        thermalIntensity: 6,
        printQuality: 'high'
      },

      // Contractor Name
      {
        id: 'contractor_name',
        type: 'text',
        x: 15,
        y: 35,
        width: 180,
        height: 25,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'variable',
        variableSource: 'visitor_name',
        fontFamily: 'thermal_default',
        fontSize: 14,
        fontWeight: 'bold',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: true,
        textOverflow: 'ellipsis',
        maxLines: 2,
        thermalIntensity: 7,
        printQuality: 'high'
      },

      // Company
      {
        id: 'contractor_company',
        type: 'text',
        x: 15,
        y: 65,
        width: 180,
        height: 18,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'variable',
        variableSource: 'visitor_company',
        fontFamily: 'thermal_default',
        fontSize: 11,
        fontWeight: 'normal',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: true,
        textOverflow: 'ellipsis',
        thermalIntensity: 6,
        printQuality: 'normal'
      },

      // Safety Box
      {
        id: 'safety_box',
        type: 'rectangle',
        x: 15,
        y: 90,
        width: 180,
        height: 70,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        borderWidth: 2,
        borderStyle: 'solid',
        borderColor: '#006600',
        fillColor: '#F0FFF0',
        cornerRadius: 5,
        thermalIntensity: 6,
        filled: true
      },

      // Safety Status 1
      {
        id: 'safety_status_1',
        type: 'text',
        x: 20,
        y: 98,
        width: 170,
        height: 12,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 2,
        contentType: 'fixed',
        fixedContent: '✓ Right to Work: VERIFIED',
        fontFamily: 'thermal_default',
        fontSize: 9,
        fontWeight: 'bold',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#006600',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 7,
        printQuality: 'normal'
      },

      // Safety Status 2
      {
        id: 'safety_status_2',
        type: 'text',
        x: 20,
        y: 115,
        width: 170,
        height: 12,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 2,
        contentType: 'fixed',
        fixedContent: '✓ H&S Induction: COMPLETE',
        fontFamily: 'thermal_default',
        fontSize: 9,
        fontWeight: 'bold',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#006600',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 7,
        printQuality: 'normal'
      },

      // Safety Status 3
      {
        id: 'safety_status_3',
        type: 'text',
        x: 20,
        y: 132,
        width: 170,
        height: 12,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 2,
        contentType: 'fixed',
        fixedContent: '✓ Insurance: VALID',
        fontFamily: 'thermal_default',
        fontSize: 9,
        fontWeight: 'bold',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#006600',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 7,
        printQuality: 'normal'
      },

      // Safety Status 4
      {
        id: 'safety_status_4',
        type: 'text',
        x: 20,
        y: 149,
        width: 170,
        height: 12,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 2,
        contentType: 'fixed',
        fixedContent: '✓ Safety Cleared',
        fontFamily: 'thermal_default',
        fontSize: 9,
        fontWeight: 'bold',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#006600',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 7,
        printQuality: 'normal'
      },

      // QR Code
      {
        id: 'qr_code',
        type: 'qr_code',
        x: 220,
        y: 45,
        width: 120,
        height: 120,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        dataType: 'visitor_data',
        includeFields: {
          visitor_id: true,
          visitor_name: true,
          company: true,
          check_in_time: true,
          expiry_time: true,
          host: true,
          purpose: true,
          phone: true,
          email: false,
          custom_fields: true
        },
        errorCorrection: 'H',
        quietZone: 3,
        moduleSize: 1,
        printMethod: 'native_qr',
        thermalIntensity: 8
      },

      // Emergency Info
      {
        id: 'emergency_info',
        type: 'text',
        x: 15,
        y: 175,
        width: 330,
        height: 12,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'fixed',
        fixedContent: 'EMERGENCY: Report to Reception immediately - Ext. 999',
        fontFamily: 'thermal_default',
        fontSize: 8,
        fontWeight: 'bold',
        fontStyle: 'normal',
        alignment: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#CC0000',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 8,
        printQuality: 'normal'
      },

      // Valid Areas
      {
        id: 'valid_areas',
        type: 'text',
        x: 15,
        y: 195,
        width: 200,
        height: 12,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'fixed',
        fixedContent: 'Valid: Authorized areas only',
        fontFamily: 'thermal_default',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 6,
        printQuality: 'normal'
      },

      // Expiry
      {
        id: 'expiry',
        type: 'text',
        x: 15,
        y: 212,
        width: 200,
        height: 12,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'variable',
        variableSource: 'expiry_date',
        fontFamily: 'thermal_default',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 6,
        printQuality: 'normal'
      },

      // Contractor ID
      {
        id: 'contractor_id',
        type: 'text',
        x: 250,
        y: 195,
        width: 100,
        height: 25,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'variable',
        variableSource: 'visitor_id',
        fontFamily: 'thermal_default',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        alignment: 'right',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 6,
        printQuality: 'normal'
      }
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: '1.0',
    isReadOnly: false
  },

  {
    id: 'visitor-minimal',
    name: 'Minimal Visitor',
    description: 'Clean, minimal design for quick visitor processing',
    category: 'visitor',
    width: 361,
    height: 247,
    backgroundColor: '#FFFFFF',
    borderEnabled: false,
    borderWidth: 0,
    borderColor: '#000000',
    compatiblePrinters: ['tec_b_fv4d', 'zebra_zt230', 'zebra_zt410'],
    elements: [
      // Simple Header
      {
        id: 'header',
        type: 'text',
        x: 20,
        y: 15,
        width: 150,
        height: 25,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'fixed',
        fixedContent: 'VISITOR',
        fontFamily: 'thermal_default',
        fontSize: 20,
        fontWeight: 'bold',
        fontStyle: 'normal',
        alignment: 'left',
        lineHeight: 1.2,
        letterSpacing: 2,
        textColor: '#000000',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 9,
        printQuality: 'high'
      },

      // Logo Placeholder
      {
        id: 'logo_minimal',
        type: 'image',
        x: 250,
        y: 10,
        width: 100,
        height: 35,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        imageType: 'company_logo',
        scaling: 'fit',
        alignment: 'center',
        brightness: 0,
        contrast: 20,
        invert: false,
        dithering: 'threshold',
        thermalIntensity: 7,
        printQuality: 'high'
      },

      // Visitor Name Large
      {
        id: 'visitor_name_large',
        type: 'text',
        x: 20,
        y: 60,
        width: 320,
        height: 35,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'variable',
        variableSource: 'visitor_name',
        fontFamily: 'thermal_default',
        fontSize: 20,
        fontWeight: 'bold',
        fontStyle: 'normal',
        alignment: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: true,
        textOverflow: 'ellipsis',
        maxLines: 2,
        thermalIntensity: 8,
        printQuality: 'high'
      },

      // Company
      {
        id: 'company_minimal',
        type: 'text',
        x: 20,
        y: 105,
        width: 200,
        height: 25,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'variable',
        variableSource: 'visitor_company',
        fontFamily: 'thermal_default',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'normal',
        alignment: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: true,
        textOverflow: 'ellipsis',
        thermalIntensity: 6,
        printQuality: 'normal'
      },

      // Date/Time Stamp
      {
        id: 'timestamp_minimal',
        type: 'text',
        x: 20,
        y: 140,
        width: 200,
        height: 20,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'variable',
        variableSource: 'check_in_time',
        fontFamily: 'thermal_default',
        fontSize: 12,
        fontWeight: 'normal',
        fontStyle: 'normal',
        alignment: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 5,
        printQuality: 'normal'
      },

      // QR Code Large
      {
        id: 'qr_large',
        type: 'qr_code',
        x: 240,
        y: 100,
        width: 100,
        height: 100,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        dataType: 'visitor_data',
        includeFields: {
          visitor_id: true,
          visitor_name: true,
          company: true,
          check_in_time: true,
          expiry_time: false,
          host: false,
          purpose: false,
          phone: false,
          email: false,
          custom_fields: false
        },
        errorCorrection: 'M',
        quietZone: 4,
        moduleSize: 1,
        printMethod: 'native_qr',
        thermalIntensity: 8
      },

      // Simple Footer
      {
        id: 'footer_minimal',
        type: 'text',
        x: 20,
        y: 215,
        width: 320,
        height: 15,
        rotation: 0,
        visible: true,
        locked: false,
        layer: 1,
        contentType: 'fixed',
        fixedContent: 'Please return this pass when leaving',
        fontFamily: 'thermal_default',
        fontSize: 10,
        fontWeight: 'normal',
        fontStyle: 'normal',
        alignment: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        textColor: '#000000',
        wordWrap: false,
        textOverflow: 'clip',
        thermalIntensity: 5,
        printQuality: 'normal'
      }
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: '1.0',
    isReadOnly: false
  }
];

// Template categories for organization
export const TEMPLATE_CATEGORIES = {
  visitor: 'Visitor Passes',
  contractor: 'Contractor Passes', 
  staff: 'Staff Passes',
  temporary: 'Temporary Passes',
  custom: 'Custom Templates'
};

// Quick template selector
export function getTemplatesByCategory(category: keyof typeof TEMPLATE_CATEGORIES) {
  return PROFESSIONAL_THERMAL_TEMPLATES.filter(template => template.category === category);
}

// Get template by ID
export function getTemplateById(id: string) {
  return PROFESSIONAL_THERMAL_TEMPLATES.find(template => template.id === id);
}

// Default template for new designs
export const DEFAULT_TEMPLATE = PROFESSIONAL_THERMAL_TEMPLATES[0];