import type { Express } from 'express';
import type { Server } from 'http';
import { registerAuthRoutes } from './auth';
import { registerPlatformAdminRoutes } from './platformAdmin';
import { registerOnboardingRoutes } from './onboarding';
import { registerVisitorRoutes } from './visitors';
import { registerStaffRoutes } from './staff';
import { registerMeetingRoomRoutes } from './meetingRooms';
import { registerReportRoutes } from './reports';
import { registerRamsRoutes } from './rams';
import { registerLoneWorkerRoutes } from './loneWorker';
import { registerSettingsRoutes } from './settings';
import { registerContractorRoutes } from './contractors';
import { registerEmergencyRoutes } from './emergency';
import { registerInductionRoutes } from './induction';
import { registerPPMRoutes } from './ppm';
import { registerRemainingRoutes } from './remaining';
import { registerAiFeatureRoutes } from './aiFeatures';
import { registerPassRoutes } from './passes';
import { registerAnalyticsRoutes } from './analytics';
import { registerImportRoutes } from './imports';
import { registerCdmRoutes } from './cdm';
import { registerHelpdeskRoutes } from './helpdesk';
import { registerHsIncidentRoutes } from './hsIncidents';
import { registerFireRiskAssessmentRoutes } from './fireRiskAssessment';
import { registerComplianceCertificateRoutes } from './complianceCertificates';
import { registerPermitToWorkRoutes } from './permitToWork';
import { registerHrStaffRoutes } from './hrStaff';
import { registerHrRightToWorkRoutes } from './hrRightToWork';
import { registerHrTrainingRoutes } from './hrTraining';
import { registerHrLeaveRoutes } from './hrLeave';
import { registerHrAbsenceRoutes } from './hrAbsence';
import { registerHrDocumentRoutes } from './hrDocuments';
import { registerHrOnboardingRoutes } from './hrOnboarding';
import { registerHrLeaverRoutes } from './hrLeaver';
import { registerHrAppraisalRoutes } from './hrAppraisals';
import { registerHrPayrollRoutes } from './hrPayroll';
import { registerHrDashboardRoutes } from './hrDashboard';
import { registerComplianceDashboardRoutes } from './complianceDashboard';
import { registerAuditEngineRoutes } from './auditEngine';
import { registerRaBuilderRoutes } from './raBuilder';
import { registerHrDbsRoutes } from './hrDbs';
import { registerSsoRoutes } from './sso';
import { registerVisitReasonRoutes } from './visitReasons';
import { registerNdaRoutes } from './nda';
import { registerTemplateLibraryRoutes } from './templateLibrary';
import { registerTeamsIntegrationRoutes } from './teamsIntegration';
import { registerCalendarIntegrationRoutes } from './calendarIntegration';
import { registerContractorPortalRoutes } from './contractorPortal';
import { registerContractorWorkerDbsRoutes } from './contractorWorkerDbs';
import { registerContractorWorkerCertsRoutes } from './contractorWorkerCerts';
import { registerContractorEquipmentRoutes } from './contractorEquipment';
import { registerBugReportRoutes } from './bugReports';
import { registerChatbotRoutes } from './chatbot';
import { registerEnterpriseSiteRoutes } from './enterpriseSites';
import { registerEnterpriseComplianceRoutes } from './enterpriseCompliance';
import { registerEnterpriseStandardsRoutes } from './enterpriseStandards';
import { registerEnterpriseContractorPoolRoutes } from './enterpriseContractorPool';
import { registerEnterpriseReportRoutes } from './enterpriseReports';
import { initComplianceEngine } from '../complianceEngine';
import { registerSeoRoutes } from '../seo';

export async function registerSplitRoutes(
  app: Express,
  server: Server,
  setupAutomaticDailyReset?: (customerId?: string) => Promise<void>
): Promise<void> {
  registerSeoRoutes(app);
  registerAuthRoutes(app);
  registerSsoRoutes(app);
  registerPlatformAdminRoutes(app);
  registerOnboardingRoutes(app);
  registerVisitorRoutes(app);
  registerStaffRoutes(app);
  registerMeetingRoomRoutes(app);
  registerReportRoutes(app);
  registerRamsRoutes(app);
  registerLoneWorkerRoutes(app, server);
  registerSettingsRoutes(app, { setupAutomaticDailyReset });
  registerContractorRoutes(app);
  registerEmergencyRoutes(app);
  registerInductionRoutes(app);
  registerPPMRoutes(app);
  registerAiFeatureRoutes(app);
  registerPassRoutes(app);
  registerAnalyticsRoutes(app);
  await registerImportRoutes(app);
  await registerCdmRoutes(app);
  registerHelpdeskRoutes(app);
  registerHsIncidentRoutes(app);
  registerFireRiskAssessmentRoutes(app);
  registerComplianceCertificateRoutes(app);
  registerComplianceDashboardRoutes(app);
  registerPermitToWorkRoutes(app);
  registerAuditEngineRoutes(app);
  registerRaBuilderRoutes(app);
  registerHrStaffRoutes(app);
  registerHrRightToWorkRoutes(app);
  registerHrTrainingRoutes(app);
  registerHrLeaveRoutes(app);
  registerHrAbsenceRoutes(app);
  registerHrDocumentRoutes(app);
  registerHrOnboardingRoutes(app);
  registerHrLeaverRoutes(app);
  registerHrAppraisalRoutes(app);
  registerHrPayrollRoutes(app);
  registerHrDashboardRoutes(app);
  registerHrDbsRoutes(app);
  registerVisitReasonRoutes(app);
  registerNdaRoutes(app);
  await registerTemplateLibraryRoutes(app);
  registerTeamsIntegrationRoutes(app);
  registerCalendarIntegrationRoutes(app);
  await registerContractorPortalRoutes(app);
  registerContractorWorkerDbsRoutes(app);
  registerContractorWorkerCertsRoutes(app);
  registerContractorEquipmentRoutes(app);
  registerBugReportRoutes(app);
  registerChatbotRoutes(app);
  registerEnterpriseSiteRoutes(app);
  registerEnterpriseComplianceRoutes(app);
  registerEnterpriseStandardsRoutes(app);
  registerEnterpriseContractorPoolRoutes(app);
  registerEnterpriseReportRoutes(app);
  initComplianceEngine();
  await registerRemainingRoutes(app, server);
}
